services:
  open3e:
    
    build:
      context: .
      dockerfile: Dockerfile

    image: ghcr.io/udochrist/open3edocker:latest
    container_name: open3e
    restart: unless-stopped
    
    # Required capabilities for CAN interface management
    cap_add:
      - NET_ADMIN
    
    devices:
      - /dev/can0:/dev/can0

    # Mount config volume for persistent data
    volumes:
      - ./config:/config
    
    # Mandatory environment variables - must be provided
    environment:
      CAN: "${CAN:-can0}"
      CLIENTID: "${CLIENTID:-open3e}"
      MQTT_HOST: "${MQTT_HOST:-mosquitto}"
      MQTT_USER: "${MQTT_USER:-mqtt_user}"
      MQTT_PASSWORD: "${MQTT_PASSWORD}"
      # use the defaults below unless you are also changing the ha integration configuration
      TOPIC: "${TOPIC:-open3e}"
      LISTENTOPIC: "${LISTENTOPIC:-open3e/cmnd}"
      FORMATSTRING: "${FORMATSTRING:-{device}_{ecuAddr:03X}_{didNumber}_{didName}}"
    
    # Healthcheck (optional)
    healthcheck:
      test: ["CMD", "/bin/sh", "/healthcheck.sh"]
      interval: 2m
      timeout: 3s
      retries: 3
      start_period: 30s
